config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index' 
  

  get 'about-us' => 'welcome#about'
  get 'our-mission' => 'welcome#ourmission'
  get 'contact-us' =>'welcome#contact'
  get 'page' => 'restaurant#page'

    
    
  
  post "restaurant" => "restaurant#show"

  
end

app/controllers/api/v1/food_controller.rb
class Api::V1::FoodController < ApplicationController
  def list
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/city_controller.rb
class CityController < ApplicationController
	def index
		@city = City.all
	end
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
   protect_from_forgery
   skip_before_action :verify_authenticity_token

   def home
   end

   def show
      @location = params[:location]
      @food_type = params[:food_type]
      options = { 
         term: @food_type,
         limit: 5,
         category_filter: 'restaurants'
      }
      response = Yelp.client.search(@location, options)

      
      @restaurant = response.businesses[0]
      @rating = response.businesses[0].rating
      @image_url = @restaurant.image_url.sub("ms.jpg", "l.jpg")
      @image = response.businesses[0].rating_img_url
      @url = response.businesses[0].url
      @address = response.businesses[0].location.display_address
      @latitude = response.businesses[0].location.coordinate.latitude
      @longitude = response.businesses[0].location.coordinate.longitude
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery
  skip_before_action :verify_authenticity_token
  
  def home
  end

  def restaurant
    @location = params[:location]
    @price_range = food_type[:food_type]
  end
end

app/helpers/api/v1/food_helper.rb
module Api::V1::FoodHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
  <style>
    body {
        border: 5px solid "light-blue lighten-3";
    }
  </style> 

   <nav class="light-blue lighten-3">
   
   <img class="logo" <%= image_tag ("brainpic.png") %>
  <a href="/" class="brand-logo">FOOD 4 THOUGHT</a> 
  

   <ul id="nav-mobile" class="right hide-on-med-and-down">
       <img class="logo2" <%= image_tag ("brainpic2.png") %>
        <li><a class="About Us" href="/about-us">About Us</a></li>
        <li><a class="Our Mission" href="/our-mission">Our Mission</a></li>
        <li><a class="Contact Us" href="/contact-us">Contact Us</a></li>

    <a id="logo-container" href="#" class="brand-logo"></a>
     
    <ul id="nav-mobile" class="right hide-on-med-and-down">
        

    
    </div>

  </nav>


</head>
<body class="<%= controller_name %> <%= action_name %>">
    
<div class="container"></div>
<br>
<br>

<%= yield %>

<script>
  
  $(document).ready(function() {
    $('select').material_select();
  });
  
  
</script>

</body>
</html>

app/views/restaurant/page.html.erb
<h3>Thanks for choosing Food 4 Thought to help satisfy your
appetite today! Enjoy your meal!</h3>

<img src="http://a.abcnews.com/images/Lifestyle/ht_empire_steak_house_kb_131231_16x9_608.jpg">

app/views/restaurant/show.html.erb
 <div align="right"
            <div class="row">
         <div class="col s4">
           <h1 align="center">GO EAT HERE!</h1>
             <h1 align="center">
	             <%= link_to @restaurant.name, @restaurant.url %> <%= image_tag @restaurant.rating_img_url %>
           </h1>

<div>
<a class="waves-effect waves-light btn" href="/page">Yes, Lets go!</a>
    <a class="waves-effect waves-light btn" href="/">No, let's try again!</a> 
    
    </div>
      </div>

<div class="col s4">
    <p align="center">
	    <%= @restaurant.location.display_address.join(" ") %>
            </p>
    <h1 align="center">
        <%= image_tag @image_url %>
            </h1>
    </div>
      
      
<div class="col s4">
    <div id="map"></div>
         <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"async defer></script>
            <script>
            var map;
            function initMap() {
            var myLatLng = new google.maps.LatLng(<%= @restaurant.location.coordinate.latitude %>, <%= @restaurant.location.coordinate.longitude  %>);
             var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 18,
            zoom: 15,
            center: myLatLng
          });

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                title: 'Go Eat!'
              });
            }
</script>
</script>   
      </div>

    </div>
     
</div>
    </div>
</div>

app/views/welcome/about.html.erb
<h4> Food 4 Thought was founded by a trio of students; Brian, Rashad, and Ash 
at the programming academy Tech Talent 
South during Spring 2016. The purpose of 
the website was to help consumers decide 
where they wanted to eat if they were ever 
feeling indecisive on how to satisfy their appetite. 
Along with the restaurant that 
shows upon entering in the information asked, a map of the location will appear and will directly link 
the restaurant name to the Yelp! profile which can also serve as another great way to determine what the ideal place to eat will be.
</h4>

<div align="center" class="main pic"><img src="https://s-media-cache-ak0.pinimg.com/736x/4d/ec/2e/4dec2e8c502eba64c558bc2cecc1df53.jpg"></div>
</body>

app/views/welcome/contact.html.erb
<h3 align="center">Questions, Comments, Cries of Outrage?</h3>
<h3 align="center">We'd love to reach out to you!</h3> 
<h3 align="center">Don't worry we won't spam your email with responses.</h3>

<h3 align="center">Created by:</h3>
  <h4 align="center">Brian Boultinghouse,<a href="bs.boultinghouse@gmail.com"> bs.boultinghouse@gmail.com</h4></a>
  <h4 align="center">Rashad Davis, <a href="rashad.davis87@yahoo.com">rashad.davis87@yahoo.com</h4></a>
  <h4 align="center">Ashwin Kumar, <a href="ashwin.k823@gamil.com">ashwin.k823@gmail.com</h4></a>

app/views/welcome/index.html.erb
  <style>
    body {background-image: url("<%= image_path('backgroundpic.png') %>") !important;}
  </style>
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>

      <h1 class="header center red-text text-lighten-2">Help us help you figure out that next meal!</h1>
        <div class="row center">
        </div>

      <h5 class="center blue-text text-lighten-2">Let's start that search.</h5>
  

      <div class="col s6">

  <form class="input-field" action="<%=restaurant_path %>" method="post">
      <div align="center" class="search">

        <div class="input-field col s6 m6">
        <input class="locator__search" name="location" placeholder ="Where are you at?" type="text" id="locationsearch" autocomplete="on">
        </div>
        <div class="input-field col s6 m6 ">
        <input class="locator__search" name="food_type" placeholder ="What food are you craving?" type="text" id="locationsearch" autocomplete="on">  
        </div>

    <input type="submit" class="locator__submit" value="Find me a place to eat!">
        <input type="submit" class="locator__submit" value="I'm so hungry, choose something random!">


    
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/geocomplete/1.7.0/jquery.geocomplete.min.js"></script>
    <script>
        $("#locationsearch").geocomplete();
    </script>
</form>

app/views/welcome/ourmission.html.erb
<h4>Our Mission is to continue providing simple, hassle-free 
ways to help you figure out where your next meal is at. It’s 
our goal to consistently narrow down choices to ultimately 
help you channel your inner foodie. Explore our website and 
help us help you decide where that next place to dine is!</h4>

<div align="center" class="other-pic"><img src="https://s-media-cache-ak0.pinimg.com/736x/80/80/ec/8080ec26b23b7501076c3639474e56b5.jpg"></div>